### ISSUE TITLE
Suggestion: Replace nested `for` loops with calls to `numpy.vectorize` in `uncertainty_bound._identify_uncertainty_upper_bound`

### ISSUE THREAD

**Issue by eid-not-die** [decargroup/dkpy#29]
This issue concerns the method `uncertainty_bound._identify_uncertainty_upper_bound` as it appears in the module `src/dkpy/uncertainty_bound.py` in the branch `feature/22-add-equivalent-of-matlabs-ucover` as of the time of this post.

The quantity `res_resp` is computed using a nested `for` loop.
```
res_resp: np.ndarray = np.zeros((ny, nu, nw, nk), dtype=complex)
    for k in range(nk):
        for w in range(nw):
            res_resp[:, :, w, k] = _form_residual_response(
                nom_resp[:, :, w],
                off_nom_resp[:, :, w, k],
                unc_str,
            )
```

The same is true for `res_msv_resp`.
```
res_msv_resp: np.ndarray = np.zeros((nw, nk))
    for k in range(nk):
        for w in range(nw):
            s = scipy.linalg.svd(a=res_resp[:, :, w, k], compute_uv=False)
            res_msv_resp[w, k] = s[0]
```

This works as intended, but is potentially very inefficient. Using `numpy.vectorize` might improve the efficiency of this computation. The use of the `signature` argument of  `numpy.vectorize` is, however, rather poorly exemplified in the documentation, in my opinion, which is where the difficulty would lie.

This issue is very low-priority.

**Comment by sdahdah** [comment]
> The [vectorize](https://numpy.org/doc/2.2/reference/generated/numpy.vectorize.html#numpy.vectorize) function is provided primarily for convenience, not for performance. The implementation is essentially a for loop.

from https://numpy.org/doc/2.2/reference/generated/numpy.vectorize.html

So you don't need to worry about it. If this part of the code ends up being really slow we can think about it more later.
